### ISSUE TITLE
Banner - Resolution Checking: no space between between banner title and menu 

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#128]
![image](https://cloud.githubusercontent.com/assets/17717843/17198196/f2a9843e-54a5-11e6-828f-ee98ad09f0ac.png)

**Comment by kraisitb** [comment]
The banner and banner content are responsive so the margin of the banner content box would depend on the browser viewport (margin top is set as 10%).

**Comment by dremensayson** [comment]
Issue exist in 1199px to 993px below resolution

**Comment by dremensayson** [comment]
issue still exist. please see new uploaded banner.

**Comment by kraisitb** [comment]
The image with the issue is an old one. You'd need to upload it again in order for the image to be cropped with dimension of 1920 x 610px. In this case since it is an old image it still has the height of 500px of which is then scaled down to about 350px on 1300px screen and affect the content box positioning.
