### ISSUE TITLE
Blog - 5 Spray Painting Tips for a Smooth, Professional Finish: incorrect permalink, it redirected to the blog page instead of single page

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#133]
![image](https://cloud.githubusercontent.com/assets/17717843/17200774/a77cc704-54ba-11e6-9c1d-d50b84518caa.png)

**Comment by dremensayson** [comment]
cannot verify the issue due to missing parent breadcrumbs link.

**Comment by kraisitb** [comment]
From issue #134 
Please note that the breadcrumb of blog single page would be 'Home / Blog 1' instead of 'Home / Blog / Blog 1'.

This is due to blog page setting of WP backend is set to empty in order to be able to display blog page editor content (basically making 'blog' a page rather than a blog).

**Comment by dremensayson** [comment]
blog page editor content has nothing to do with the breadcrumbs. please see sample site for the implementation. http://austecelectrical-imp.stage.titanweb.com.au/blog/
