### ISSUE TITLE
Gallery: Please make 3 columns when resolution reaches from 640 to 767

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/TLC-Surface-Treatment#95]
![image](https://cloud.githubusercontent.com/assets/17717843/16793517/2df8c3f4-4904-11e6-8de7-19caeba18abb.png)

**Comment by kraisitb** [comment]
By default we follow the following viewport breakpoint:
- 993px - 1200px or larger
- 992px or lower
- 768px or lower
- 480px or lower

640 to 767 would fall into the case of 768 or lower so that is why the images are displaying 2 per row. If possible I prefer not to create a specific case of viewport range to handle elements (it is mentioned in our checklist not to do so as well).

**Comment by dremensayson** [comment]
hi kraisit,
yes we are aware of the breakpoint, but the problem is the page is to spacious that can accommodate 1 more image with same size.
Please refer to this website:
http://jcglass.stage.titanweb.com.au/gallery/
